name: Build Android App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'
          cache: 'npm'

      - name: Clean npm cache & remove lockfile/node_modules
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Bundle JS & Build Release APK
        run: |
          # generate JS bundle and assets (so APK doesn't need Metro)
          mkdir -p android/app/src/main/assets
          mkdir -p android/app/src/main/res
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

          # build release APK (bundled JS will be included)
          cd android
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Upload Release APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
